// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6XGQ4YyaPDLjgCjCcxx9lrNDObMriojE',
    appId: '1:293464700678:web:85b67766ebd11b77a35087',
    messagingSenderId: '293464700678',
    projectId: 'bomb-chat-6da2d',
    authDomain: 'bomb-chat-6da2d.firebaseapp.com',
    storageBucket: 'bomb-chat-6da2d.firebasestorage.app',
    measurementId: 'G-K66YG7CRZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3e9nL3yCMV88uEUAawtAT1NMQziyHChI',
    appId: '1:293464700678:android:ff0f365e44fd3829a35087',
    messagingSenderId: '293464700678',
    projectId: 'bomb-chat-6da2d',
    storageBucket: 'bomb-chat-6da2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRdRTCBQV_6CB4k057x9ZarMNOE5YbTE',
    appId: '1:293464700678:ios:ec73d7712b48c307a35087',
    messagingSenderId: '293464700678',
    projectId: 'bomb-chat-6da2d',
    storageBucket: 'bomb-chat-6da2d.firebasestorage.app',
    iosBundleId: 'com.example.bombChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRdRTCBQV_6CB4k057x9ZarMNOE5YbTE',
    appId: '1:293464700678:ios:ec73d7712b48c307a35087',
    messagingSenderId: '293464700678',
    projectId: 'bomb-chat-6da2d',
    storageBucket: 'bomb-chat-6da2d.firebasestorage.app',
    iosBundleId: 'com.example.bombChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6XGQ4YyaPDLjgCjCcxx9lrNDObMriojE',
    appId: '1:293464700678:web:446e6ba3c3f77315a35087',
    messagingSenderId: '293464700678',
    projectId: 'bomb-chat-6da2d',
    authDomain: 'bomb-chat-6da2d.firebaseapp.com',
    storageBucket: 'bomb-chat-6da2d.firebasestorage.app',
    measurementId: 'G-6F29QWDB2V',
  );
}
